// Generated by deploy.ps1 — do not edit by hand.
// Environment is sourced from .env.prod on the deploying machine.
module.exports = {
  apps: [
    {
      name: 'oneweb-backend',
      cwd: '/home/onetap/oneweb/publish',
      // Run through bash: pointing PM2 straight at the dll makes it try to
      // exec the file itself ("cannot execute binary file").
      script: 'bash',
      args: ['-c', 'exec dotnet OneWeb.Api.dll'],
      interpreter: 'none',
      env: {
        ASPNETCORE_URLS: 'http://127.0.0.1:5102',
      "ASPNETCORE_ENVIRONMENT": "Production",
      "TZ": "Asia/Dhaka",
      "FRONTEND_URL": "http://104.248.232.169/web",
      "API_PUBLIC_BASE_URL": "http://104.248.232.169",
      "PAYMENT_ALLOWED_RETURN_ORIGINS": "http://104.248.232.169",
      "POSTGRES_HOST": "postgres",
      "POSTGRES_PORT": "5432",
      "POSTGRES_DB": "oneweb",
      "POSTGRES_USER": "postgres",
      "POSTGRES_PASSWORD": "KJFiMFjI9FCUtlBn5xYaKqrkIblP",
      "CONNECTIONSTRINGS__DEFAULT": "Host=localhost;Port=5433;Database=oneweb;Username=postgres;Password=KJFiMFjI9FCUtlBn5xYaKqrkIblP",
      "REDIS__CONNECTIONSTRING": "localhost:6379",
      "JWT__SECRETKEY": "YourSuperSecretKeyHereMinimum32Characters!",
      "JWT__ISSUER": "OneWeb",
      "JWT__AUDIENCE": "OneWebUsers",
      "JWT__ACCESSTOKENEXPIRYMINUTES": "60",
      "JWT__REFRESHTOKENEXPIRYDAYS": "7",
      "MASTERAUTH__ENABLED": "true",
      "SSLWIRELESS_API_BASE": "https://smsplus.sslwireless.com",
      "SSLWIRELESS_SID": "ONETAPSERVICEBRAND",
      "SSLWIRELESS_API_KEY": "ngycabv6-uvz4o4o1-seg47hmg-xuswqyho-aa98j6ir",
      "SSLWIRELESS_SENDER_ID": "ONETAPSERVICEBRAND",
      "SSLWIRELESS_NONMASKING_SENDER": "",
      "SSLWIRELESS_DLR_WEBHOOK_URL": "https://api.onetapservice.com/v1/sms/dlr",
      "SSLWIRELESS_MASKING_ENABLED": "true",
      "SSLWIRELESS_NONMASKING_ENABLED": "false",
      "SSLWIRELESSL_USER": "FHR",
      "SSLWIRELESS_PASSWORD": "1234567",
      "SSLWIRELESS_MESSAGE_TYPE": "EN",
      "DLR_WEBHOOK_URL": "https://api.onetapservice.com/v1/sms/dlr",
      "SSLCOMMERZ_STORE_ID": "labai69d4e6bc24ef7",
      "SSLCOMMERZ_STORE_PASSWORD": "labai69d4e6bc24ef7@ssl",
      "SSLCOMMERZ_API_VERSION": "4",
      "SSLCOMMERZ_API_BASE_URL": "https://sandbox.sslcommerz.com",
      "SSLCOMMERZ_VALIDATION_BASE_URL": "https://sandbox.sslcommerz.com",
      "SSLCOMMERZ_REFUND_BASE_URL": "https://sandbox.sslcommerz.com",
      "SSLCOMMERZ_CURRENCY": "BDT",
      "SPACES_ACCESS_KEY_ID": "DO00DHT8X6EU2DGCWPWV",
      "SPACES_SECRET_ACCESS_KEY": "QNWy2bRQHfwv8apH6b2yUD5wWGFUqIKLkTxfZOb7JNY",
      "SPACES_BUCKET_NAME": "lcst",
      "SPACES_REGION": "sgp1",
      "SPACES_ENDPOINT": "https://sgp1.digitaloceanspaces.com",
      "SPACES_CDN_ENDPOINT": "https://lcst.sgp1.cdn.digitaloceanspaces.com",
      "SPACES_ROOT_FOLDER": "Onetap",
      "NEXT_PUBLIC_API_URL": "http://104.248.232.169",
      "BKASH__BASEURL": "https://tokenized.sandbox.bka.sh/v2",
      "BKASH__USERNAME": "01770618567",
      "BKASH__PASSWORD": "D7DaC<*E*eG",
      "BKASH__APPKEY": "0vWQuCRGiUX7EPVjQDr0EUAYtc",
      "BKASH__APPSECRET": "jcUNPBgbcqEDedNKdvE4G1cAK7D3hCjmJccNPZZBq96QIxxwAMEx",
      "BULKSMS__SENDERID": "8809648908931",
      "BULKSMS__API_KEY": "pUnGy1xfE77G1YicFYM7",
      "NEXT_BASE_PATH": "/web",
      "NEXT_PUBLIC_CDN_URL": "https://lcst.sgp1.cdn.digitaloceanspaces.com/Onetap/web",
      "MAPBOX_ACCESS_TOKEN": "sk.eyJ1IjoiZmFoYXJhMDIiLCJhIjoiY21zM29waWZkMDNpNTJ5cjRxbDQwdTV1MiJ9.FlSYLxYcfzk-vDV80NL0Hw",
      "MAPBOX_STYLE_ID": "mapbox/streets-v12",
      "MAPBOX_PK_TOKEN": "pk.eyJ1IjoiZmFoYXJhMDIiLCJhIjoiY21uYXd3M3ZjMG15NjJycXlndW9mZDU3OSJ9._VhQ5z13K8RAo44d_AW_sw",
      "NEXT_PUBLIC_MAPBOX_TOKEN": "pk.eyJ1IjoiZmFoYXJhMDIiLCJhIjoiY21uYXd3M3ZjMG15NjJycXlndW9mZDU3OSJ9._VhQ5z13K8RAo44d_AW_sw",
      "NEXT_PUBLIC_MAPBOX_STYLE_ID": "mapbox/streets-v12",
      "NEXT_PUBLIC_DEFAULT_LOCATION": "Green Road, Dhaka",
      "NEXT_PUBLIC_DEFAULT_LAT": "23.7509",
      "NEXT_PUBLIC_DEFAULT_LNG": "90.3854",
      "NEXT_PUBLIC_GEOCODE_COUNTRY": "bd",
      "NEXT_PUBLIC_CDN_PORTAL_URL": "https://lcst.sgp1.cdn.digitaloceanspaces.com/Onetap/portal",
      "PORTAL_BASE_PATH": "/portal",
      "PORTAL_PUBLIC_URL": "http://104.248.232.169/portal",
      "NEXT_PUBLIC_BARIKOI_KEY": "",
      "NEXT_PUBLIC_GOOGLE_MAPS_KEY": ""
      }
    },
    {
      name: 'oneweb-web',
      cwd: '/home/onetap/oneweb/web',
      script: 'server.js',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
        HOSTNAME: '127.0.0.1'
      }
    },
    {
      name: 'oneweb-portal',
      cwd: '/home/onetap/oneweb/portal',
      script: 'server.js',
      env: {
        NODE_ENV: 'production',
        PORT: '3002',
        HOSTNAME: '127.0.0.1'
      }
    }
  ]
}
