// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneWeb.Infrastructure.Persistence;

#nullable disable

namespace OneWeb.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806041143_LanguagesAndServiceTranslations")]
    partial class LanguagesAndServiceTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneWeb.Domain.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_addresses_user_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppContent")
                        .HasColumnType("text")
                        .HasColumnName("app_content");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("text")
                        .HasColumnName("meta_keywords");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blogs");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_blogs_category_id");

                    b.ToTable("blogs", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.BlogCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blog_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_categories_slug");

                    b.ToTable("blog_categories", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.BlogTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppContent")
                        .HasColumnType("text")
                        .HasColumnName("app_content");

                    b.Property<long>("BlogId")
                        .HasColumnType("bigint")
                        .HasColumnName("blog_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Lang")
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blog_translations");

                    b.HasIndex("BlogId")
                        .HasDatabaseName("ix_blog_translations_blog_id");

                    b.ToTable("blog_translations", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.BusinessSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Lang")
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_business_settings");

                    b.ToTable("business_settings", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CommissionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AdminAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("admin_amount");

                    b.Property<double>("CommissionAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("commission_amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("VendorAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("vendor_amount");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_commission_histories");

                    b.ToTable("commission_histories", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("text")
                        .HasColumnName("discount_type");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<double?>("MaxDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("max_discount");

                    b.Property<double?>("MinimumPurchase")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum_purchase");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("Id")
                        .HasName("pk_coupons");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CouponUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coupon_usages");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_coupon_usages_order_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_coupon_usages_user_id");

                    b.HasIndex("CouponId", "UserId")
                        .HasDatabaseName("ix_coupon_usages_coupon_id_user_id");

                    b.ToTable("coupon_usages", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CustomPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("text")
                        .HasColumnName("meta_keywords");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text")
                        .HasColumnName("meta_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("web")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_custom_pages");

                    b.HasIndex("Link")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_pages_link");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_custom_pages_slug");

                    b.ToTable("custom_pages", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CustomPageTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Lang")
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_custom_page_translations");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_custom_page_translations_page_id");

                    b.ToTable("custom_page_translations", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BnName")
                        .HasColumnType("text")
                        .HasColumnName("bn_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("division_id");

                    b.Property<string>("Lat")
                        .HasColumnType("text")
                        .HasColumnName("lat");

                    b.Property<string>("Long")
                        .HasColumnType("text")
                        .HasColumnName("long");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_districts_division_id");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Division", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BnName")
                        .HasColumnType("text")
                        .HasColumnName("bn_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_divisions");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.FcmToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_fcm_tokens");

                    b.ToTable("fcm_tokens", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NativeName")
                        .HasColumnType("text")
                        .HasColumnName("native_name");

                    b.Property<bool>("Rtl")
                        .HasColumnType("boolean")
                        .HasColumnName("rtl");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additional_info");

                    b.Property<long?>("AfterPic")
                        .HasColumnType("bigint")
                        .HasColumnName("after_pic");

                    b.Property<long?>("AssignResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("assign_resource_id");

                    b.Property<long?>("BeforePic")
                        .HasColumnType("bigint")
                        .HasColumnName("before_pic");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("CommissionCalculated")
                        .HasColumnType("integer")
                        .HasColumnName("commission_calculated");

                    b.Property<double>("CouponDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("coupon_discount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("Date")
                        .HasColumnType("bigint")
                        .HasColumnName("date");

                    b.Property<string>("DeliverStatusJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("deliver_status_json");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("delivery_status");

                    b.Property<int>("DeliveryViewed")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_viewed");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("grand_total");

                    b.Property<int>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("is_cancelled");

                    b.Property<string>("Latitude")
                        .HasColumnType("text")
                        .HasColumnName("latitude");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<string>("Longitude")
                        .HasColumnType("text")
                        .HasColumnName("longitude");

                    b.Property<string>("OrderFrom")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("app")
                        .HasColumnName("order_from");

                    b.Property<string>("PaymentDetails")
                        .HasColumnType("text")
                        .HasColumnName("payment_details");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("unpaid")
                        .HasColumnName("payment_status");

                    b.Property<int>("PaymentStatusViewed")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status_viewed");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<long>("PriceId")
                        .HasColumnType("bigint")
                        .HasColumnName("price_id");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text")
                        .HasColumnName("shipping_address");

                    b.Property<string>("ShippingType")
                        .HasColumnType("text")
                        .HasColumnName("shipping_type");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.Property<string>("TrackingCode")
                        .HasColumnType("text")
                        .HasColumnName("tracking_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.Property<int>("Viewed")
                        .HasColumnType("integer")
                        .HasColumnName("viewed");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("DeliveryStatus")
                        .HasDatabaseName("ix_orders_delivery_status");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_orders_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_orders_service_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_orders_vendor_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("text")
                        .HasColumnName("coupon_code");

                    b.Property<double?>("CouponDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("coupon_discount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DeliveryCharge")
                        .HasColumnType("double precision")
                        .HasColumnName("delivery_charge");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<double?>("Tax")
                        .HasColumnType("double precision")
                        .HasColumnName("tax");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order_details");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_details_order_id");

                    b.ToTable("order_details", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long?>("OrderId1")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id1");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_order_id");

                    b.HasIndex("OrderId1")
                        .HasDatabaseName("ix_payments_order_id1");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<double?>("RatingValue")
                        .HasColumnType("double precision")
                        .HasColumnName("rating_value");

                    b.Property<string>("Review")
                        .HasColumnType("text")
                        .HasColumnName("review");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_ratings");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_ratings_order_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ratings_user_id");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<string>("BannerImage")
                        .HasColumnType("text")
                        .HasColumnName("banner_image");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("double precision")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("FAQ")
                        .HasColumnType("text")
                        .HasColumnName("faq");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("text")
                        .HasColumnName("hero_subtitle");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("text")
                        .HasColumnName("hero_title");

                    b.Property<double>("InitialPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("initial_price");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trending");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("text")
                        .HasColumnName("meta_keywords");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text")
                        .HasColumnName("meta_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("PriceUnit")
                        .HasColumnType("text")
                        .HasColumnName("price_unit");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("ServiceIcon")
                        .HasColumnType("text")
                        .HasColumnName("service_icon");

                    b.Property<string>("ServiceQuality")
                        .HasColumnType("text")
                        .HasColumnName("service_quality");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_services_slug");

                    b.HasIndex("ParentId", "Level", "Status")
                        .HasDatabaseName("ix_services_parent_id_level_status");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.ServicePrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_prices");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_prices_service_id");

                    b.ToTable("service_prices", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.ServiceSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<string>("EndTime")
                        .HasColumnType("text")
                        .HasColumnName("end_time");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<string>("StartTime")
                        .HasColumnType("text")
                        .HasColumnName("start_time");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_schedules");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_schedules_service_id");

                    b.ToTable("service_schedules", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.ServiceTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("FAQ")
                        .HasColumnType("text")
                        .HasColumnName("faq");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("text")
                        .HasColumnName("hero_subtitle");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("text")
                        .HasColumnName("hero_title");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceQuality")
                        .HasColumnType("text")
                        .HasColumnName("service_quality");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_translations");

                    b.HasIndex("ServiceId", "Lang")
                        .IsUnique()
                        .HasDatabaseName("ix_service_translations_service_id_lang");

                    b.ToTable("service_translations", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Slider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text")
                        .HasColumnName("sub_title");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sliders");

                    b.ToTable("sliders", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_support_tickets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_support_tickets_user_id");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Upazila", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BnName")
                        .HasColumnType("text")
                        .HasColumnName("bn_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_upazilas");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_upazilas_district_id");

                    b.ToTable("upazilas", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Upload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_uploads");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long?>("AssignVendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("assign_vendor_id");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text")
                        .HasColumnName("blood_group");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceVersion")
                        .HasColumnType("text")
                        .HasColumnName("device_version");

                    b.Property<string>("Dob")
                        .HasColumnType("text")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FcmId")
                        .HasColumnType("text")
                        .HasColumnName("fcm_id");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("ImageId")
                        .HasColumnType("text")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<string>("Latitude")
                        .HasColumnType("text")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .HasColumnType("text")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_type");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text")
                        .HasColumnName("verification_code");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Vendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcademicCertificate")
                        .HasColumnType("text")
                        .HasColumnName("academic_certificate");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("balance");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("text")
                        .HasColumnName("bank_account_name");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<int?>("BankPaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("bank_payment_status");

                    b.Property<string>("BankRoutingNumber")
                        .HasColumnType("text")
                        .HasColumnName("bank_routing_number");

                    b.Property<string>("BinNumber")
                        .HasColumnType("text")
                        .HasColumnName("bin_number");

                    b.Property<int?>("CashPaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("cash_payment_status");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("double precision")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cv")
                        .HasColumnType("text")
                        .HasColumnName("cv");

                    b.Property<long?>("District")
                        .HasColumnType("bigint")
                        .HasColumnName("district");

                    b.Property<long?>("Division")
                        .HasColumnType("bigint")
                        .HasColumnName("division");

                    b.Property<bool>("MobilePaymentStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("mobile_payment_status");

                    b.Property<string>("Nid")
                        .HasColumnType("text")
                        .HasColumnName("nid");

                    b.Property<double>("PendingBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("pending_balance");

                    b.Property<string>("ShortBiography")
                        .HasColumnType("text")
                        .HasColumnName("short_biography");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("TinNumber")
                        .HasColumnType("text")
                        .HasColumnName("tin_number");

                    b.Property<double>("TotalEarnings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("total_earnings");

                    b.Property<string>("TradeLicense")
                        .HasColumnType("text")
                        .HasColumnName("trade_license");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("text")
                        .HasColumnName("work_experience");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_user_id");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.VendorService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_services");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_vendor_services_service_id");

                    b.HasIndex("VendorId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_services_vendor_id_service_id");

                    b.ToTable("vendor_services", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.VendorWithdrawRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_withdraw_requests");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_vendor_withdraw_requests_vendor_id");

                    b.ToTable("vendor_withdraw_requests", (string)null);
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Address", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_addresses_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Blog", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.BlogCategory", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_blogs_blog_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.BlogTranslation", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Blog", "Blog")
                        .WithMany("Translations")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blog_translations_blogs_blog_id");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CouponUsage", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_usages_coupons_coupon_id");

                    b.HasOne("OneWeb.Domain.Entities.Order", "Order")
                        .WithOne()
                        .HasForeignKey("OneWeb.Domain.Entities.CouponUsage", "OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_coupon_usages_orders_order_id");

                    b.HasOne("OneWeb.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_usages_users_user_id");

                    b.Navigation("Coupon");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CustomPageTranslation", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.CustomPage", "Page")
                        .WithMany("Translations")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_page_translations_custom_pages_page_id");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.District", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_districts_divisions_division_id");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Order", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Service", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_services_service_id");

                    b.HasOne("OneWeb.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Order", "Order")
                        .WithOne("Detail")
                        .HasForeignKey("OneWeb.Domain.Entities.OrderDetail", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_details_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Payment", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Order", null)
                        .WithOne("Payment")
                        .HasForeignKey("OneWeb.Domain.Entities.Payment", "OrderId")
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.HasOne("OneWeb.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId1")
                        .HasConstraintName("fk_payments_orders_order_id1");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Rating", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Order", null)
                        .WithOne("Rating")
                        .HasForeignKey("OneWeb.Domain.Entities.Rating", "OrderId")
                        .HasConstraintName("fk_ratings_orders_order_id");

                    b.HasOne("OneWeb.Domain.Entities.User", null)
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_ratings_users_user_id");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Service", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Service", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_services_services_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.ServicePrice", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Service", "Service")
                        .WithMany("Prices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_prices_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.ServiceSchedule", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Service", "Service")
                        .WithMany("Schedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_schedules_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.ServiceTranslation", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_translations_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_support_tickets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Upazila", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_upazilas_districts_district_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.User", "User")
                        .WithOne("Vendor")
                        .HasForeignKey("OneWeb.Domain.Entities.Vendor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendors_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.VendorService", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_services_services_service_id");

                    b.HasOne("OneWeb.Domain.Entities.Vendor", "Vendor")
                        .WithMany("VendorServices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_services_vendors_vendor_id");

                    b.Navigation("Service");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.VendorWithdrawRequest", b =>
                {
                    b.HasOne("OneWeb.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_withdraw_requests_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Blog", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.CustomPage", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Order", b =>
                {
                    b.Navigation("Detail");

                    b.Navigation("Payment");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Service", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Orders");

                    b.Navigation("Prices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("OneWeb.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("VendorServices");
                });
#pragma warning restore 612, 618
        }
    }
}
